<a href="https://colab.research.google.com/github/KosachevAN/CSHARP/blob/main/Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#1.
import numpy as np

In [14]:
#a. Создайте массив из 10 нулей
ar0 = np.zeros(10, dtype=np.int8)
ar0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [15]:
#b. Создать массив из 10 единиц
ar1 = np.ones(10, dtype=np.int8)
ar1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [16]:
#c. Создать массив из 10 пятерок
ar5 = np.linspace(5, 5, 10, dtype=np.int8)
ar5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int8)

In [17]:
#d. Создать массив из целых чисел от 10 до 50
ar = np.arange(10, 51)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [18]:
#e. Создать массив из четных чисел от 10 до 50
ar = np.arange(10, 51, 2)
ar

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
#f. Создать матрицу 3х3 с числами от 0 до 8
ar = np.arange(9)
ar = ar.reshape(3, 3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
#g. Создать единичную матрицу 3x3
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#h. Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения
a = np.random.random(25)
a

array([0.63985302, 0.1492324 , 0.4997509 , 0.16687788, 0.44565166,
       0.66734593, 0.5729577 , 0.48329585, 0.11064809, 0.72438268,
       0.27632873, 0.57174506, 0.16439109, 0.45799928, 0.16993086,
       0.14611276, 0.09643873, 0.88147409, 0.53834733, 0.38674381,
       0.70293994, 0.92442841, 0.53510306, 0.10637818, 0.39313256])

In [22]:
#i. Создайте следующую матрицу используя функции библиотеки NumPy
a = np.linspace(0, 1, 100, dtype=np.float16)
a = a.reshape(10,10)
a

array([[0.    , 0.0101, 0.0202, 0.0303, 0.0404, 0.0505, 0.0606, 0.0707,
        0.0808, 0.0909],
       [0.101 , 0.1111, 0.1212, 0.1313, 0.1414, 0.1515, 0.1616, 0.1718,
        0.1818, 0.1919],
       [0.202 , 0.2122, 0.2222, 0.2323, 0.2424, 0.2524, 0.2627, 0.2727,
        0.2827, 0.293 ],
       [0.303 , 0.3132, 0.3232, 0.3333, 0.3435, 0.3535, 0.3635, 0.3738,
        0.3838, 0.394 ],
       [0.404 , 0.414 , 0.4243, 0.4343, 0.4443, 0.4546, 0.4646, 0.4749,
        0.4849, 0.4949],
       [0.505 , 0.515 , 0.5254, 0.535 , 0.5454, 0.5557, 0.5654, 0.5757,
        0.586 , 0.596 ],
       [0.606 , 0.616 , 0.6265, 0.636 , 0.6465, 0.6567, 0.6665, 0.677 ,
        0.687 , 0.697 ],
       [0.707 , 0.7173, 0.727 , 0.7373, 0.7476, 0.758 , 0.7676, 0.778 ,
        0.788 , 0.798 ],
       [0.808 , 0.8184, 0.828 , 0.8384, 0.8486, 0.8584, 0.8687, 0.879 ,
        0.8887, 0.899 ],
       [0.909 , 0.9194, 0.929 , 0.9395, 0.9497, 0.9595, 0.9697, 0.98  ,
        0.9897, 1.    ]], dtype=float16)

In [23]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
#j
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [25]:
#k. Написать код обращения к элементу который вернет значение 20 из стартовой матрицы задачи l.
mat[3, 4]

20

In [26]:
#l
mat[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [27]:
#m
mat[4,0:]

array([21, 22, 23, 24, 25])

In [28]:
#n
mat[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
#o
mat.sum()

325

In [30]:
#p
np.std(mat, axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [32]:
np.std(mat, axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [33]:
np.std(mat)

7.211102550927978

In [34]:
#q
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])